<div class="container">
    <div style="padding-top: 15px; padding-bottom: 10px">
        <div class='row-fluid'>
            <div style='color: #6C747F'>
                <div class="col-lg-9">
                    &copy; 2016 On Point Performance Center. All rights reserved.
                </div>
                <div class="col-lg-3">
                    <div style='text-align: right'>
                     Home / About Us / Contact Us
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

