<footer class="footer">
    <div class="container">
            <div class='row-fluid'>
                <div style="padding-top: 15px; padding-bottom: 10px">
                    <div class="col-lg-7">
                        <a href="./">Home</a> / <a href="./forms">Forms</a> / <a href="./about">About Us</a> / <a href="./contact">Contact Us</a>
                    </div>
                    <div class="col-lg-5">
                        <div class="col-lg-6">
                            <div style="text-align: right">
                                <img src="./assets/images/logo_white.png" height="50" width="50" />
                            </div>
                        </div>
                        <div class="col-lg-6">
                            On Point Performance Center</br>
                            567-B North Cameron St<br />
                            Winchester, VA 22601
                        </div>
                    </div>
                </div>
            </div>
            <div class='row-fluid'>
                <div class="col-lg-9">
                    &copy; <?php echo date("Y") ?> On Point Performance Center
                </div>
                <div class="col-lg-3">                                     
            </div>
    </div>
</footer>
